const KEY='comparador-bicicletas-v1';
let bikes=readBikes();
let selectorMode='edit';
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
function readBikes(){try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}}
function writeBikes(){localStorage.setItem(KEY,JSON.stringify(bikes));$('#storageStatus').textContent='Salvo localmente ✓'}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(v){const n=Number(v);return Number.isFinite(n)&&n>0?n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'Preço não informado'}
function clean(v){return String(v??'').trim()}
function id(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function route(name){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+name+'View').classList.add('active');location.hash=name==='home'?'home':name;window.scrollTo({top:0,behavior:'smooth'});if(name==='home')renderHome()}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2500)}
function summary(b){const title=[b.marca,b.modelo].filter(Boolean).join(' ')||'Bike sem identificação';return `<article class="bike-card" data-id="${b.id}"><span class="badge">${esc(b.uso||'Opção cadastrada')}</span><h3>${esc(title)}</h3><p><strong>Loja:</strong> ${esc(b.loja||'Não informada')}</p><p><strong>Quadro:</strong> ${esc(b.quadro||b.materialQuadro||'Não informado')}</p><p class="price">${money(b.precoVista)}</p></article>`}
function renderHome(){const n=bikes.length;$('#bikeCount').textContent=n?`${n} bicicleta${n===1?'':'s'} cadastrada${n===1?'':'s'} neste navegador.`:'Nenhuma bike cadastrada ainda.';$('#recentBikes').innerHTML=bikes.slice().reverse().map(summary).join('');$('#clearAllBtn').hidden=!n;$$('#recentBikes .bike-card').forEach(c=>c.onclick=()=>openForm(c.dataset.id))}
function renderSelector(){const action=selectorMode==='edit'?'editar':'exportar';$('#selectorKicker').textContent=selectorMode==='edit'?'Edição':'Exportação';$('#selectorTitle').textContent=`Escolha uma bicicleta para ${action}`;$('#selectorHelp').textContent=selectorMode==='edit'?'Clique em um card para abrir o formulário.':'Clique em um card para copiar o relatório em Markdown.';$('#selectorBikes').innerHTML=bikes.map(summary).join('');$('#emptySelector').hidden=!!bikes.length;$$('#selectorBikes .bike-card').forEach(c=>c.onclick=()=>selectorMode==='edit'?openForm(c.dataset.id):copyOne(c.dataset.id))}
function blank(){return {id:id(),dataConsulta:new Date().toISOString().slice(0,10)}}
function openForm(bikeId=null){const b=bikeId?bikes.find(x=>x.id===bikeId):blank();if(!b)return;const form=$('#bikeForm');form.reset();$('#bikeId').value=b.id;Object.entries(b).forEach(([k,v])=>{const el=form.elements[k];if(el)el.value=v??''});const editing=!!bikeId;$('#formMode').textContent=editing?'Editando dados':'Nova pesquisa';$('#formTitle').textContent=editing?'Editar bicicleta':'Adicionar bicicleta';$('#deleteBtn').hidden=!editing;$('#saveMessage').textContent='Salvamento local ativo: cada alteração é gravada imediatamente.';route('form')}
function formData(){const form=$('#bikeForm');const b={id:$('#bikeId').value||id()};[...new FormData(form).entries()].forEach(([k,v])=>b[k]=v);return b}
function autosave(){const b=formData();const pos=bikes.findIndex(x=>x.id===b.id);if(pos<0)bikes.push(b);else bikes[pos]={...bikes[pos],...b};writeBikes();$('#saveMessage').textContent=`Salvo automaticamente às ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}.`;renderHome()}
function mdLine(label,value){return clean(value)?`| ${label} | ${String(value).replace(/\|/g,'\\|').replace(/\n/g,'<br>')} |\n`:''}
function bikeMarkdown(b){const title=[b.marca,b.modelo].filter(Boolean).join(' ')||'Bicicleta sem identificação';let out=`# ${title}\n\n`;
out+=`> Registro criado no Comparador de Bicicletas${b.dataConsulta?` em ${new Date(b.dataConsulta+'T12:00:00').toLocaleDateString('pt-BR')}`:''}.\n\n`;
out+='## Resumo de compra\n\n| Campo | Informação |\n|---|---|\n';[['Loja',b.loja],['Marca',b.marca],['Modelo',b.modelo],['Tamanho do quadro',b.tamanhoQuadro],['Uso pretendido',b.uso],['Preço à vista',money(b.precoVista)],['Preço a prazo',money(b.precoPrazo)],['Parcelamento sem juros',b.parcelamento],['Formas de pagamento',b.pagamento],['Frete',money(b.frete)],['Montagem/revisão',money(b.montagem)],['Montagem',b.montagemStatus]].forEach(x=>out+=mdLine(...x));
const groups=[['Quadro, suspensão e direção',[['Quadro',b.quadro],['Material',b.materialQuadro],['Garantia do quadro',b.garantiaQuadro],['Garfo/suspensão',b.garfo],['Tipo/curso da suspensão',b.suspensao],['Caixa de direção',b.caixaDirecao],['Guidão',b.guidao],['Mesa/avanço',b.mesa],['Canote',b.canote]]],['Rodas, pneus e freios',[['Aros',b.aros],['Cubo dianteiro',b.cuboDianteiro],['Cubo traseiro',b.cuboTraseiro],['Sistema traseiro',b.sistemaTraseiro],['Raios',b.raios],['Pneus',b.pneus],['Freio dianteiro',b.freioDianteiro],['Freio traseiro',b.freioTraseiro],['Marca dos freios',b.freiosMarca]]],['Transmissão',[['Velocidades',b.velocidades],['Trocadores',b.trocadores],['Câmbio dianteiro',b.cambioDianteiro],['Câmbio traseiro',b.cambioTraseiro],['Catraca/cassete',b.catraca],['Corrente',b.corrente],['Pedivela',b.pedivela],['Movimento central',b.movimentoCentral],['Pedais',b.pedais]]],['Conforto e garantia',[['Selim',b.selim],['Peso',clean(b.peso)?`${b.peso} kg`:'' ],['Limite de peso',clean(b.limitePeso)?`${b.limitePeso} kg`:'' ],['Garantia do garfo',b.garantiaGarfo],['Garantia dos componentes',b.garantiaComponentes],['Pós-venda',b.posVenda],['Nota pessoal',clean(b.nota)?`${b.nota}/10`:'' ]]];
groups.forEach(([name,items])=>{out+=`\n## ${name}\n\n| Campo | Informação |\n|---|---|\n`;items.forEach(x=>out+=mdLine(...x))});if(clean(b.positivos))out+=`\n## Pontos positivos\n\n${b.positivos}\n`;if(clean(b.negativos))out+=`\n## Pontos negativos / riscos\n\n${b.negativos}\n`;if(clean(b.observacoes))out+=`\n## Observações\n\n${b.observacoes}\n`;return out}
function allMarkdown(){let out='# Comparativo de Bicicletas\n\n';if(!bikes.length)return out+'Nenhuma bicicleta cadastrada.\n';out+='| Bike | Loja | Preço à vista | Parcelamento | Quadro | Rodas/Pneus | Transmissão | Freios | Nota |\n|---|---|---:|---|---|---|---|---|---:|\n';bikes.forEach(b=>{const name=[b.marca,b.modelo].filter(Boolean).join(' ')||'Sem nome';const wheels=[b.aros,b.pneus].filter(Boolean).join('; ');const brakes=[b.freioDianteiro,b.freioTraseiro].filter(Boolean).join('; ');out+=`| ${name} | ${clean(b.loja)||'-'} | ${money(b.precoVista)} | ${clean(b.parcelamento)||'-'} | ${clean(b.quadro)||clean(b.materialQuadro)||'-'} | ${wheels||'-'} | ${clean(b.velocidades)||'-'} | ${brakes||'-'} | ${clean(b.nota)||'-'} |\n`});out+='\n## Detalhes individuais\n';bikes.forEach(b=>out+=`\n---\n\n${bikeMarkdown(b)}`);return out}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Markdown copiado para a área de transferência.')}catch{const a=document.createElement('textarea');a.value=text;document.body.append(a);a.select();document.execCommand('copy');a.remove();toast('Markdown copiado para a área de transferência.')}}
function copyOne(bikeId){const b=bikes.find(x=>x.id===bikeId);if(b)copy(bikeMarkdown(b))}
$$('[data-route]').forEach(x=>x.onclick=e=>{e.preventDefault();route(x.dataset.route)});$$('[data-action]').forEach(x=>x.onclick=()=>{const a=x.dataset.action;if(a==='add')openForm();else if(a==='edit'||a==='export-one'){selectorMode=a==='edit'?'edit':'export';renderSelector();route('selector')}else if(a==='export-all')copy(allMarkdown())});
$('#bikeForm').addEventListener('input',autosave);$('#bikeForm').addEventListener('change',autosave);$('#doneBtn').onclick=()=>{autosave();route('home');toast('Bike salva com sucesso.')} ;$('#copyCurrentBtn').onclick=()=>{autosave();copyOne($('#bikeId').value)};$('#deleteBtn').onclick=()=>{const b=bikes.find(x=>x.id===$('#bikeId').value);if(b&&confirm(`Excluir ${[b.marca,b.modelo].filter(Boolean).join(' ')||'esta bicicleta'}?`)){bikes=bikes.filter(x=>x.id!==b.id);writeBikes();route('home');toast('Bicicleta excluída.')}};$('#clearAllBtn').onclick=()=>{if(confirm('Excluir todas as bicicletas salvas neste navegador?')){bikes=[];writeBikes();renderHome();toast('Todos os dados foram excluídos.')}};
renderHome();
